parameters:
  "service-dir":
    default: "sdk/applink"
emit:
- "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    # azure-resource-provider-folder: "resource-manager"
    emit-common-types-schema: "never"
    # `arm-resource-flattening` is only used for back-compat for specs existed on July 2024. All new service spec should NOT use this flag
    # arm-resource-flattening: true
    # emitter-output-dir: "{project-root}/.."
    arm-types-dir: "{project-root}/../../common-types/resource-management"
    # output-file: "{azure-resource-provider-folder}/{service-name}/fleet/{version-status}/{version}/fleets.json"
    omit-unreachable-types: true
    # use-read-only-status-schema: true
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/applink/{version-status}/{version}/applink.json"
  "@azure-tools/typespec-go":
    # service-dir: "sdk/resourcemanager/containerservicefleet"
    # package-dir: "armcontainerservicefleet"
    # module: "github.com/Azure/azure-sdk-for-go/{service-dir}/{package-dir}"
    # fix-const-stuttering: true
    # flavor: "azure"
    # generate-samples: true
    # generate-fakes: true
    # head-as-boolean: true
    # inject-spans: true
    service-dir: "sdk/resourcemanager/applink"
    package-dir: "armapplink"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/{package-dir}"
    fix-const-stuttering: true
    flavor: "azure"
    generate-samples: false
    generate-fakes: false
    head-as-boolean: true
    inject-spans: true

# linter:
#   extends:
#   - "@azure-tools/typespec-azure-rulesets/resource-manager"
