parameters:
  "service-dir":
    default: "sdk/applink"
emit:
- "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/contoso.json"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/applink"
    package-dir: "armapplink"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/{package-dir}"
    fix-const-stuttering: true
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
linter:
  extends:
  - "@azure-tools/typespec-azure-rulesets/resource-manager"
